package xiaoqian.controller;
<<<<<<< HEAD

import org.json.JSONException;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

import org.springframework.web.client.RestTemplate;
import xiaoqian.model.User;
import xiaoqian.repository.UserRepository;

import lombok.extern.slf4j.Slf4j;

import java.net.URLEncoder;

@Slf4j        // Adding this, you can use log.info and output your announcement in the console
@Controller // This means that this class is a Controller
@RequestMapping(path="/user") // This means URL's start with /demo (after Application path)
public class UserController {
	
	// This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	@Autowired
	private UserRepository userRepository;

	@Value("${wechat.mpAppId}")
	private String appId;
	@Value("${wechat.mpAppSecret}")
	private String appSecret;

	@RequestMapping(value="/wechat/auth")
	public void authRequest() {
		String backurl = "http://www.aidologist.com/user/wechat/callback";
		String url = "https://open.weixin.qq.com/connect/oauth2/authorize" +
				"?appid=" + appId +
				"&redirect_uri=" + URLEncoder.encode(backurl) +
				"&response_type=" + "code" +
				"&scope=" + "snsapi_userinfo" +
				"&state=" + "STATE#wechat_redirect";
		RestTemplate restTemplate = new RestTemplate();
		restTemplate.getForObject(url, String.class);
	}

	@RequestMapping(value="/wechat/callback")
	public void callBack(@RequestParam("code") String code) throws JSONException {
		String url = "https://api.weixin.qq.com/sns/oauth2/access_token" +
				"?appid=" + appId +
				"&secret=" + appSecret +
				"&code=" + code +
				"&grant_type=" + "authorization_code";
		RestTemplate restTemplate = new RestTemplate();
		String reponse = restTemplate.getForObject(url, String.class);
		JSONObject json = new JSONObject(reponse);
		String openid = json.getString("openid");
		String token = json.getString("access_token");
		String pullinfoUrl = "https://api.weixin.qq.com/sns/userinfo" +
				"?access_token=" + token +
				"&openid=" + openid +
				"&lang=zh_CN";
		restTemplate = new RestTemplate();
		reponse = restTemplate.getForObject(pullinfoUrl, String.class);
		json = new JSONObject(reponse);
	}

	@RequestMapping(value="/phone/insert")
	public User insertPhone(@RequestParam("phoneNum") String phoneNum) throws JSONException {
		return userRepository.findByPhoneNum(phoneNum);
	}

	@RequestMapping(value="/phone/login")
	public void loginPhone(@RequestParam("phone") String code) throws JSONException {

	}

}
=======
//
//import org.json.JSONException;
//import org.json.JSONObject;
//import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.beans.factory.annotation.Value;
//import org.springframework.stereotype.Controller;
//import org.springframework.web.bind.annotation.RequestMapping;
//import org.springframework.web.bind.annotation.RequestParam;
//
//import org.springframework.web.client.RestTemplate;
//import xiaoqian.repository.UserRepository;
//
//import lombok.extern.slf4j.Slf4j;
//
//import java.net.URLEncoder;
//
//@Slf4j        // Adding this, you can use log.info and output your announcement in the console
//@Controller // This means that this class is a Controller
//@RequestMapping(path="/user") // This means URL's start with /demo (after Application path)
//public class UserController {
//	
//	// This means to get the bean called userRepository
//	// Which is auto-generated by Spring, we will use it to handle the data
//	@Autowired
//	private UserRepository userRepository;
//
//	@Value("${wechat.mpAppId}")
//	private String appId;
//	@Value("${wechat.mpAppSecret}")
//	private String appSecret;
//
//	@RequestMapping(value="/wechat/auth")
//	public void authRequest() {
//		String backurl = "http://www.aidologist.com/user/wechat/callback";
//		String url = "https://open.weixin.qq.com/connect/oauth2/authorize" +
//				"?appid=" + appId +
//				"&redirect_uri=" + URLEncoder.encode(backurl) +
//				"&response_type=" + "code" +
//				"&scope=" + "snsapi_userinfo" +
//				"&state=" + "STATE#wechat_redirect";
//		RestTemplate restTemplate = new RestTemplate();
//		restTemplate.getForObject(url, String.class);
//	}
//
//	@RequestMapping(value="/wechat/callback")
//	public void callBack(@RequestParam("code") String code) throws JSONException {
//		String url = "https://api.weixin.qq.com/sns/oauth2/access_token" +
//				"?appid=" + appId +
//				"&secret=" + appSecret +
//				"&code=" + code +
//				"&grant_type=" + "authorization_code";
//		RestTemplate restTemplate = new RestTemplate();
//		String reponse = restTemplate.getForObject(url, String.class);
//		JSONObject json = new JSONObject(reponse);
//		String openid = json.getString("openid");
//		String token = json.getString("access_token");
//		String pullinfoUrl = "https://api.weixin.qq.com/sns/userinfo" +
//				"?access_token=" + token +
//				"&openid=" + openid +
//				"&lang=zh_CN";
//		restTemplate = new RestTemplate();
//		reponse = restTemplate.getForObject(pullinfoUrl, String.class);
//		json = new JSONObject(reponse);
//	}
//
//}
>>>>>>> 96fc00265ffe07ce3695d9142873eccc761c4529
